version: '3.9'

services:
   game:
     build:
       context: ./game
       dockerfile: Dockerfile
     command: python3 -m server.py
     volumes:
       - ./game:/code/game
     ports:
       - 8000:8000
   nginx:
     build: ./nginx
     network_mode: host
     volumes:
       - ./game:/code/game
     depends_on:
       - game